wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32]
    rows: [10, 10, 10]
  refreshInterval: 1
  mods:
    yfinance:
      enabled: true
      title: "Stock and exchange rate 🚀"
      sort: true
      refreshInterval: 1m
      symbols:
        - "DOCN"
        - "GLE.PA"
        - "ABN.AS"
        - "ICAD.PA"
        - "ACA.PA"
        - "ORA.PA"
        - "USDCAD=X"
        - "CADUSD=X"
      position:
        top: 2
        left: 0
        height: 2
        width: 3
    feedreader:
      enabled: true
      feeds:
      - http://feeds.bbci.co.uk/news/rss.xml
      feedLimit: 10
      position:
        top: 1
        left: 0
        width: 3
        height: 1
      refreshInterval: 14400
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    spotify:
      enabled: true
      colors:
        label: "green"
        text: "white"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 0
